"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const candidato_js_1 = require("../classes/candidato.js");
const listaDeCandidatos_1 = require("./listaDeCandidatos");
const form = document.getElementById('form-candidato');
form.addEventListener("submit", function (event) {
    event.preventDefault();
    console.log('evento submit chamdo');
    const nome = document.getElementById('nome').value;
    const email = document.getElementById('email').value;
    const idade = document.getElementById('idade').value;
    const cpf = document.getElementById('cpf').value;
    const estado = document.getElementById('estado').value;
    const cep = document.getElementById('cep').value;
    const competencias = document.getElementById('competencia').value;
    const descricao = document.getElementById('descricao').value;
    let novoUsuarioC = new candidato_js_1.Candidato(nome, email, Number(idade), cpf, estado, cep, descricao, competencias);
    listaDeCandidatos_1.candidatos.push(novoUsuarioC);
    console.log('candidato cadastrado com sucesso!');
    console.log({ nome, email, idade, cpf, estado, cep, competencias, descricao });
});
